controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

api_login_check:
    path: /authentication_token
    methods: [ 'POST' ]
    defaults:
        _format: json 
